"""Topic vocabularies for the topic classifier (EN and ES routes).

Transcribed verbatim from the Oracle workflow's TOPIC_CLASSIFICATION_SCRIPT (v2.4)
and TOPIC_CLASSIFICATION_SCRIPT_SPANISH (v2.5-ES) code nodes.  Each topic vocabulary
has three weighted buckets:

    uni  -> weight 1   (supporting single-word signal)
    uniS -> weight 2   (strong single-word signal)
    bi   -> weight 3   (two-word phrase, most specific)

A trailing ``*`` means prefix match.
"""

from __future__ import annotations

# ===========================================================================
# ENGLISH ROUTE (TOPIC_CLASSIFICATION_SCRIPT)
# ===========================================================================
EN = {
    "answer_node_candidates": ["ANSWER_AGENT_", "ANSWER_AGENT", "RETURN_AGENT_RESPONSE"],
    "stopwords_extra_es": [
        "favor", "puede", "pueden", "tengo", "tiene", "quisiera", "necesito", "yo",
    ],
    "workforce": ["tavern", "represented", "nonrep", "nonrepresented", "rep"],
    "balance_regex": r"\b(do i have|have i got|i have left|have left|remaining|balance|saldo|me quedan|tengo acumulad\w*|tengo disponibl\w*)\b",
    "first_person_regex": r"\b(my|mi|mis|i|im|yo|tengo|me quedan)\b",
    "audience_workforce_order": False,  # ES-only rule "empleados representados"
    "vocab": {
        "V_CRISIS": {
            "uniS": ["suicid*", "911", "emergenc*", "ambulance", "ambulancia", "overdose",
                     "depress*", "deprimid*", "depresion", "hopeless*",
                     "gun", "knife", "weapon", "stab*", "shoot*", "violence", "violent",
                     "arma", "pistola", "cuchillo", "matarme", "suicidio", "violencia"],
            "uni": ["die", "dying", "threat*", "amenaz*", "bleeding", "unconscious", "morir",
                    "anxious", "anxiety", "ansiedad", "overwhelmed", "crying", "worthless"],
            "bi": ["kill myself", "hurt myself", "hurt someone", "hurt somebody", "end my",
                   "my life", "want die", "not breathing", "heart attack", "threatened me",
                   "going hurt", "quiero morir", "hacerme dano", "me amenazo", "amenazo me",
                   "no respira", "me quiero", "panic attack", "feeling down", "cant cope",
                   "ataque panico", "me siento mal"],
        },
        "V_HARASSMENT": {
            "uniS": ["harass*", "discriminat*", "racis*", "sexis*", "bully*", "bullie*",
                     "intimidat*", "retaliat*", "slur*", "homophob*", "groping", "groped",
                     "acos*", "hostigamiento", "discrimina*", "intimidaci*", "represalia*",
                     "hostil*"],
            "uni": ["inappropriate", "unwanted", "creepy", "targeted", "mocking"],
            "bi": ["hostile environment", "hostile work", "unwanted touching",
                   "unwanted advances", "unwanted comments", "inappropriate touching",
                   "inappropriate comments", "inappropriate jokes", "inappropriate signs",
                   "inappropriate gestures", "inappropriate messages",
                   "inappropriate pictures", "inappropriate photos", "sexual comments",
                   "sexual advances", "comentarios sexuales", "ambiente hostil"],
        },
        "V_UNION": {
            "uniS": ["unioniz*", "strike", "striking", "picket*", "walkout", "weingarten",
                     "nlrb", "sindicaliz*", "huelga"],
            "uni": [],
            "bi": ["join union", "joining union", "form union", "forming union",
                   "start union", "starting union", "create union", "organize union",
                   "organizing union", "union vote", "union election", "union card",
                   "union rep", "union representative", "union representation",
                   "union steward", "union drive", "collective bargaining",
                   "bargaining unit", "right organize", "labor organizing",
                   "afiliarme sindicato", "afiliarse sindicato", "unirme sindicato",
                   "formar sindicato", "crear sindicato", "negociacion colectiva",
                   "representacion sindical", "delegado sindical", "paro laboral"],
        },
        "V_DISPUTE": {
            "uniS": ["appeal*", "grievance*", "griev*", "overturn", "contest*", "impugnar",
                     "apelar", "apelacion", "disputar"],
            "uni": ["escalate", "escalating", "reverse", "unfairly", "wrongly", "wrongful*",
                    "injustamente", "revertir"],
            "bi": ["dispute decision", "disagree decision", "fight decision",
                   "reverse decision", "challenge decision", "change decision",
                   "unfair termination", "unfair writeup", "unfair write",
                   "unfairly fired", "unfairly terminated", "unfairly suspended",
                   "wrongly fired", "wrongly terminated", "fired unfairly",
                   "terminated unfairly", "suspended unfairly", "written unfairly",
                   "wrongful termination", "despido injustificado",
                   "despedido injustamente", "injustamente despedido",
                   "no acuerdo", "acuerdo decision", "suspension injusta"],
        },
        "V_COMPLAINT": {
            "uniS": ["complain*", "queja*", "quejar*", "inconform*", "insatisfech*",
                     "yell*", "grita*", "rude", "disrespect*", "grosero*",
                     "unethical", "misconduct", "wrongdoing", "antietic*"],
            "uni": ["unhappy", "dissatisfied", "frustrat*", "annoyed",
                    "terrible", "awful", "dirty", "unsafe", "filthy", "ridiculous",
                    "unacceptable", "unfair", "molest*",
                    "hart*", "injust*", "sucio*", "horrible"],
            "bi": ["fed up", "sick of", "tired of", "break room", "working conditions",
                   "condiciones trabajo", "report unethical", "unethical work",
                   "unethical behavior", "report misconduct", "report problem",
                   "report issue", "report concern", "reportar problema",
                   "reportar irregularidad"],
        },
        "V_PERSONAL_DATA": {
            "uniS": ["paystub*", "w2", "1095", "1099", "payslip*", "expediente", "balance", "saldo"],
            "uni": ["address", "phone", "email", "beneficiar*", "withholding", "pl",
                    "remaining", "left", "quedan",
                    "update", "change", "correct*", "fix", "edit", "view", "show", "access",
                    "wrong", "incorrect", "outdated",
                    "direccion", "telefono", "correo", "actualizar", "cambiar", "corregir*",
                    "correccion*", "arreglar", "ver", "mostrar", "equivocad*", "incorrect*",
                    "falta*", "desactualizad*"],
            "bi": ["pay stub", "pay stubs", "pay slip", "check stub", "direct deposit",
                   "bank account", "routing number", "emergency contact",
                   "emergency contacts", "personal information", "personal info",
                   "personal data", "personal records", "legal name", "marital status",
                   "talon pago", "recibo pago",
                   "recibo nomina", "deposito directo", "cuenta bancaria",
                   "contacto emergencia", "contactos emergencia", "datos personales",
                   "informacion personal",
                   "many pl", "pl left", "pl balance", "pl remaining", "pto balance",
                   "pto left", "days left", "days remaining", "hours left", "vacation left",
                   "sick left", "points left", "time left",
                   "cuantos pl", "cuantas horas", "me quedan", "quedan dias", "dias quedan"],
        },
        "V_POLICY": {
            "uniS": ["polic*", "politica*", "handbook", "manual", "vacation*", "vacaciones",
                     "pto", "pl", "holiday*", "feriado*", "festivo*", "bereavement", "fmla",
                     "maternity", "paternity", "maternidad", "paternidad", "baby", "pregnan*",
                     "embarazad*", "bebe", "parto", "military", "militar", "accident*",
                     "injur*", "illness*", "enfermedad*", "medical", "clinic*",
                     "tattoo*", "tatuaje*", "piercing*", "uniform*", "grooming", "attire", "clothing",
                     "paydate*", "payday*", "payroll", "nomina", "overtime", "benefit*",
                     "beneficio*", "insurance", "seguro", "401k", "tuition", "licencia",
                     "schedule*", "horario*", "turno*", "shift*", "attendance", "asistencia",
                     "tardy", "tardiness", "smoking", "fumar", "parking", "estacionamiento",
                     "badge", "gafete", "credencial", "incapacidad", "duelo", "permiso"],
            "uni": ["rule*", "regla*", "paid", "pagan", "pagar", "break*", "descanso*",
                    "lunch", "almuerzo", "dress", "vestimenta", "procedure*", "guideline*",
                    "points", "puntos", "late", "tardanza*", "notice", "calling", "workplace",
                    "center", "hospital", "died", "death", "funeral", "posting", "deployment",
                    "photo*", "camera*", "money", "dinero"],
            "bi": ["pay date", "pay dates", "pay day", "pay period", "pay schedule",
                   "when paid", "get paid", "dress code", "sick leave", "sick day",
                   "sick days", "sick time", "paid time", "time off", "day off", "days off",
                   "floating holiday", "jury duty", "leave absence", "meal period",
                   "call out", "call off", "clock in", "clock out", "name tag",
                   "cell phone", "double time", "shift differential", "no call",
                   "fecha pago", "fechas pago", "dia pago", "dias pago", "cuando pagan",
                   "payment date", "payment dates", "payment schedule", "arriving late",
                   "arrive late", "showing up", "lost money", "found money", "found lost",
                   "lost item", "found item", "lost property", "dinero perdido",
                   "dinero encontrado", "objetos perdidos", "critical illness",
                   "enfermedad grave", "codigo vestimenta", "horas extra", "horas extras",
                   "dia libre", "reportar enfermo", "llegar tarde"],
        },
        "V_META": {
            "uniS": ["chatbot"],
            "uni": ["robot", "bot", "ai", "limitations", "capabilities", "funcionas"],
            "bi": ["you do", "you help", "you work", "you know", "you answer",
                   "your sources", "your limitations", "your capabilities",
                   "your training", "your knowledge", "who made", "who created",
                   "who built", "made you", "created you", "built you", "you robot",
                   "you bot", "you ai", "you human", "you real", "this work", "how work",
                   "puedes hacer", "como funcionas", "eres robot", "eres bot", "eres ia",
                   "eres humano", "tus fuentes", "quien creo", "te creo", "te hizo"],
        },
        "V_CLARIFICATION": {
            "uniS": ["rephrase", "reword", "elaborate", "clarify", "repite*", "aclarar"],
            "uni": ["translate", "spanish", "english", "espanol", "ingles", "simpler"],
            "bi": ["you mean", "what mean", "that mean", "explain again", "explain more",
                   "explain further", "say again", "repeat that", "more detail",
                   "more details", "simple terms", "simpler terms", "plain english",
                   "dont understand", "didnt understand", "not understand", "dont get",
                   "didnt get", "not follow", "break down", "no entiendo", "no entendi",
                   "otra vez", "mas detalle", "mas detalles", "mas despacio",
                   "quieres decir", "otras palabras", "explica nuevo", "explicame nuevo"],
        },
        "V_ACK": {
            "uniS": ["hi", "hello", "hey", "hola", "thanks", "thank", "thx", "ty", "gracias",
                     "ok", "okay", "bye", "goodbye", "adios", "understood", "entendido",
                     "vale", "listo", "perfecto", "perfect", "great", "awesome", "cool",
                     "welcome", "buenas"],
            "uni": ["good", "morning", "afternoon", "evening", "night", "acuerdo", "bien"],
            "bi": ["got it", "sounds good", "good morning", "good afternoon",
                   "good evening", "good night", "see you", "take care", "will do",
                   "buenos dias", "buenas tardes", "buenas noches", "hasta luego",
                   "nos vemos", "muy bien", "esta bien", "muchas gracias"],
        },
        "V_HR_ISH": {
            "uniS": ["hr", "payroll"],
            "uni": ["work", "job", "manager", "supervisor", "employee", "employees", "pay",
                    "paycheck", "company", "casino", "property", "team", "boss", "coworker",
                    "trabajo", "empleo", "jefe", "empleado", "pago", "empresa", "gerente"],
            "bi": ["human resources", "recursos humanos", "team member"],
        },
    },
}


# ===========================================================================
# SPANISH ROUTE (TOPIC_CLASSIFICATION_SCRIPT_SPANISH)
# ===========================================================================
ES = {
    "answer_node_candidates": ["ANSWER_AGENT_SPANISH"],
    "stopwords_extra_es": [
        "favor", "puede", "pueden", "puedo", "podria", "debo", "deberia", "voy",
        "tengo", "tiene", "quisiera", "necesito", "yo", "para", "este", "esto", "eso",
        "esa", "ese", "sobre", "ha", "han", "sido",
    ],
    "workforce": ["tavern", "taberna", "taverna",
                  "represented", "nonrep", "nonrepresented", "rep",
                  "representado", "representados", "representada", "representadas",
                  "sindicalizado", "sindicalizados", "sindicalizada", "sindicalizadas"],
    "balance_regex": r"\b(do i have|have i got|i have left|have left|remaining|balance|saldo|me quedan|me restan|tengo acumulad\w*|tengo disponibl\w*)\b|\bcuant[oa]s?\b[^.?!]{0,30}\b(tengo|me quedan|me restan)\b",
    "first_person_regex": r"\b(my|mi|mis|i|im|yo|me|tengo)\b",
    "audience_workforce_order": True,
    "vocab": {
        "V_CRISIS": {
            "uniS": ["suicid*", "911", "emergenc*", "ambulancia", "sobredosis", "infarto",
                     "pistola", "arma", "cuchillo", "navaja", "disparar*", "apunala*",
                     "violencia", "violent*", "matarme", "matarse", "deprimid*", "depresion",
                     "desesperad*", "angustia*", "autolesion*", "lastimarme", "overdose"],
            "uni": ["morir", "muriendo", "morirme", "amenaz*", "sangrando", "inconsciente",
                    "ansiedad", "ansios*", "abrumad*", "llorando", "desmay*"],
            "bi": ["quiero morir", "quiero morirme", "me quiero", "hacerme dano",
                   "me amenazo", "amenazo me", "no respira", "ataque panico",
                   "ataque corazon", "me siento mal", "me golpeo", "me pego",
                   "quiero lastimarme", "no aguanto", "quiero matarme"],
        },
        "V_HARASSMENT": {
            "uniS": ["acos*", "hostigamiento", "hostigar*", "hostigand*", "discrimina*",
                     "racis*", "sexis*", "homofob*", "intimidaci*", "intimidar*",
                     "intimidand*", "represalia*", "burla*", "humilla*", "maltrat*",
                     "manosea*", "toqueteo", "bullying", "hostil*"],
            "uni": ["inapropiad*", "ofensiv*", "vulgar*", "obscen*", "morbos*"],
            "bi": ["ambiente hostil", "trato hostil", "comentarios sexuales",
                   "insinuaciones sexuales", "avances sexuales",
                   "comentarios inapropiados", "gestos inapropiados",
                   "senas inapropiadas", "mensajes inapropiados", "fotos inapropiadas",
                   "chistes inapropiados", "tocamientos indebidos", "me toca",
                   "me sigue", "sentir incomoda", "sentir incomodo"],
        },
        "V_UNION": {
            "uniS": ["huelga", "huelguista*", "piquete*", "weingarten", "nlrb",
                     "sindicalizar", "sindicalizarme", "sindicalizarnos", "sindicalizarse",
                     "sindicalizacion"],
            "uni": [],
            "bi": ["afiliarme sindicato", "afiliarse sindicato", "afiliarnos sindicato",
                   "unirme sindicato", "unirse sindicato", "meterme sindicato",
                   "entrar sindicato", "formar sindicato", "crear sindicato",
                   "organizar sindicato", "negociacion colectiva", "contrato colectivo",
                   "convenio colectivo", "representacion sindical", "delegado sindical",
                   "representante sindical", "voto sindical", "eleccion sindical",
                   "tarjeta sindical", "paro laboral", "hacer huelga",
                   "derechos sindicales", "derecho organiz*"],
        },
        "V_DISPUTE": {
            "uniS": ["apelar", "apelacion*", "apelo", "impugnar", "disputar", "revocar",
                     "grievance*"],
            "uni": ["escalar", "revertir", "injustamente", "reclam*", "despido", "despedid*",
                    "suspension", "suspend*", "sancion*"],
            "bi": ["apelar decision", "impugnar decision", "disputar decision",
                   "revertir decision", "cambiar decision", "pelear decision",
                   "no acuerdo", "acuerdo decision", "despido injustificado",
                   "despido injusto", "despedido injustamente", "injustamente despedido",
                   "suspension injusta", "sancion injusta", "reporte injusto",
                   "terminacion injusta", "decision equivocada", "no procede",
                   "queja formal"],
        },
        "V_COMPLAINT": {
            "uniS": ["quej*", "inconform*", "insatisfech*", "grita*", "grito*", "grosero*",
                     "irrespetuos*", "denunci*", "antietic*", "maleducad*"],
            "uni": ["molest*", "enojad*", "cansad*", "hart*", "frustrad*", "injust*",
                    "suci*", "terrible", "horrible", "pesim*", "asquero*", "insegur*",
                    "ridicul*", "inaceptable"],
            "bi": ["cuarto descanso", "sala descanso", "condiciones trabajo",
                   "malas condiciones", "mal comportamiento", "comportamiento antietico",
                   "presentar queja", "poner queja", "levantar queja",
                   "reportar problema", "reportar irregularidad"],
        },
        "V_PERSONAL_DATA": {
            "uniS": ["talon*", "paystub*", "w2", "1095", "1099", "expediente", "saldo",
                     "balance", "comprobante*"],
            "uni": ["direccion", "domicilio", "telefono", "celular", "correo", "email",
                    "beneficiari*", "retencion*", "pl", "restan", "quedan",
                    "actualiz*", "cambi*", "modific*", "corregir*", "correccion*",
                    "consult*", "revis*", "arreglar", "ver", "mostrar", "muestr*",
                    "equivocad*", "incorrect*", "erroneo", "erronea", "falta*",
                    "desactualizad*"],
            "bi": ["talon pago", "talon cheque", "recibo pago", "recibo nomina",
                   "comprobante pago", "comprobante nomina", "deposito directo",
                   "cuenta bancaria", "numero cuenta", "contacto emergencia",
                   "contactos emergencia", "datos personales", "informacion personal",
                   "mi informacion", "mis datos", "mi expediente", "mi direccion",
                   "mi domicilio", "mi telefono", "mi celular", "mi correo",
                   "correo mi", "telefono mi", "direccion mi", "email mi", "numero mi",
                   "estado civil", "nombre legal", "retencion impuestos",
                   "formulario w2", "saldo vacaciones", "vacaciones disponibles",
                   "dias disponibles", "horas disponibles", "me quedan", "quedan dias",
                   "dias quedan", "cuantos pl", "cuanto pl", "cuantas horas"],
        },
        "V_POLICY": {
            "uniS": ["politica*", "reglamento*", "norma*", "manual", "vacacion*", "pto", "pl",
                     "feriado*", "festivo*", "asueto*", "fmla", "incapacidad*", "licencia*",
                     "permiso*", "maternidad", "paternidad", "embarazo", "embarazad*",
                     "bebe", "parto", "militar", "accidente*", "accident*", "lesion*",
                     "enfermedad*", "medic*", "clinica*", "tatuaje*", "perforacion*",
                     "piercing*", "uniforme*", "nomina", "aguinaldo", "prestacion*",
                     "propina*", "jubilacion", "pension*", "seguro*", "beneficio*",
                     "horario*", "turno*", "asistencia", "retardo*", "tardanza*",
                     "puntualidad", "fumar", "estacionamiento", "gafete", "credencial",
                     "reportarme", "reportandome", "ausentarme", "ausenci*",
                     "capacitacion", "entrenamiento", "payday*", "paydate*", "401k",
                     "duelo", "foto*", "fotografia*", "camara*"],
            "uni": ["regla*", "pagan", "pagar", "descanso*", "almuerzo", "break*", "lunch",
                    "puntos", "tarde", "aviso", "anticipacion", "fallec*", "muri*", "muerte",
                    "funeral", "luto", "dinero", "centro", "hospital", "celular"],
            "bi": ["fecha pago", "fechas pago", "dia pago", "dias pago", "cuando pagan",
                   "dia libre", "dias libres", "tiempo libre", "codigo vestimenta",
                   "horas extra", "horas extras", "tiempo extra", "doble tiempo",
                   "marcar entrada", "marcar salida", "checar entrada", "checar salida",
                   "hora entrada", "hora salida", "hora comida", "periodo comida",
                   "reportar enfermo", "llegar tarde", "llegando tarde",
                   "centro medico", "atencion medica", "seguro medico",
                   "licencia militar", "servicio militar", "puesto militar",
                   "permiso escolar", "actividades escolares", "aviso previo",
                   "cuanta anticipacion", "pedir permiso", "pedir tiempo",
                   "tomar fotos", "sacar fotos", "tomar fotografias",
                   "dinero perdido", "dinero encontrado", "objetos perdidos",
                   "enfermedad grave", "dia festivo", "dias festivos", "dias feriados",
                   "uso celular", "sin avisar", "no presentarse"],
        },
        "V_META": {
            "uniS": ["chatbot"],
            "uni": ["robot", "bot", "ia", "funcionas", "limitaciones", "capacidades",
                    "haces", "sabes"],
            "bi": ["puedes hacer", "puedes ayudar", "como funcionas", "como trabajas",
                   "donde obtienes", "eres robot", "eres bot", "eres ia", "eres humano",
                   "eres real", "un robot", "una ia", "inteligencia artificial",
                   "tus fuentes", "tus limitaciones", "tus capacidades", "quien creo",
                   "quien hizo", "te creo", "te hizo", "como respondes"],
        },
        "V_CLARIFICATION": {
            "uniS": ["repite*", "aclarar", "aclara*", "parafrasea*", "reformula*",
                     "significa", "dijiste"],
            "uni": ["traduc*", "espanol", "ingles", "sencillo", "simple", "despacio",
                    "explicam*"],
            "bi": ["significa eso", "quieres decir", "no entiendo", "no entendi",
                   "no comprendo", "no comprendi", "otra vez", "explica nuevo",
                   "explicame nuevo", "mas detalle", "mas detalles", "mas despacio",
                   "mas simple", "mas sencillo", "mas claro", "otras palabras",
                   "palabras simples", "dime mas", "explicame mas"],
        },
        "V_ACK": {
            "uniS": ["hola", "gracias", "ok", "okay", "okey", "vale", "listo", "perfecto",
                     "entendido", "comprendido", "recibido", "adios", "genial", "excelente",
                     "buenas", "chao", "sale"],
            "uni": ["bueno", "bien", "acuerdo", "va"],
            "bi": ["buenos dias", "buenas tardes", "buenas noches", "buen dia",
                   "hasta luego", "hasta manana", "nos vemos", "muy bien", "esta bien",
                   "todo bien", "muchas gracias", "mil gracias", "gracias mil"],
        },
        "V_HR_ISH": {
            "uniS": ["rh", "hr", "nomina"],
            "uni": ["trabajo", "empleo", "jefe", "jefa", "empleado*", "gerente",
                    "supervisor*", "companero*", "empresa", "casino", "propiedad",
                    "departamento", "gerencia", "sueldo", "quincena", "equipo", "pago"],
            "bi": ["recursos humanos", "miembro equipo"],
        },
    },
}


CONFIG = {"EN": EN, "ES": ES}
